name = "rozvrh-api"
main = "src/index.js"
compatibility_date = "2026-03-13"

[placement]
mode = "smart"

[vars]
TIMETABLE_URL = "https://znamky.gmh.cz/timetable/public/Actual/class/PJ?ShowCaption=0&ShowFilter=1&TouchMode=1&showTerm=1"
NEXT_TIMETABLE_URL = "https://znamky.gmh.cz/Timetable/Public/Next/Class/PJ?showCaption=0&showFilter=1&showTerm=1"
CLASS_4A_URL = "https://znamky.gmh.cz/timetable/public/Actual/class/PR?ShowCaption=0&ShowFilter=1&TouchMode=1&showTerm=1"
CLASS_4A_NEXT_URL = "https://znamky.gmh.cz/Timetable/Public/Next/Class/PR?showCaption=0&showFilter=1&showTerm=1"
STRAVA_MENU_URL = "https://app.strava.cz/en/jidelnicky?jidelna=0059"

[assets]
directory = "./public"

[[d1_databases]]
binding = "timetable_db"
database_name = "timetable_db"
database_id = "d19428d5-0415-4a62-a7a3-bc67ea02647e"

[triggers]
crons = ["*/2 * * * *"]

