name = "rozvrh-gmh"
pages_build_output_dir = "public"
compatibility_date = "2026-03-19"

[placement]
mode = "smart"

[vars]
TIMETABLE_BASE_URL = "https://znamky.gmh.cz/Timetable/Public"
DISCOVERY_URL = "https://znamky.gmh.cz/Timetable/Public"
TIMETABLE_URL = "https://znamky.gmh.cz/timetable/public/Actual/class/PY?ShowCaption=0&ShowFilter=1&TouchMode=1&showTerm=1"
NEXT_TIMETABLE_URL = "https://znamky.gmh.cz/Timetable/Public/Next/Class/PY?showCaption=0&showFilter=1&showTerm=1"
CLASS_4A_URL = "https://znamky.gmh.cz/timetable/public/Actual/class/PZ?ShowCaption=0&ShowFilter=1&TouchMode=1&showTerm=1"
CLASS_4A_NEXT_URL = "https://znamky.gmh.cz/Timetable/Public/Next/Class/PZ?showCaption=0&showFilter=1&showTerm=1"
STRAVA_MENU_URL = "https://www.strava.cz/strava5/Jidelnicky/XML?zarizeni=0059"

[[services]]
binding = "WORKER_API"
service = "rozvrh-api"
